import type { Metadata } from "next";
import { Bruno_Ace } from "next/font/google";
import "./globals.css";

const bruno = Bruno_Ace({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-bruno",
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={bruno.className}> 
        {children}
      </body>
    </html>
  );
}